# blender_builder.py
# DXF pts_mm + Room 배치 → Blender 3D 씬 생성
#
# 두 가지 모드:
#   1. generate_script(...)  → Blender Python 스크립트 문자열 반환 (MCP / subprocess 용)
#   2. build_blend_scene(...) → 내부에서 bpy 직접 실행 (Blender 인터프리터 내부 실행 시)
#
# 파이프라인:
#   pts_mm (외곽) → 바닥 슬랩(Slab) + 외벽 압출(Extrude)
#   rooms        → 내벽 + 바닥 구역 색상 분할
#   천장          → 외곽 폴리곤 상단 캡
#   카메라/조명   → 기본 씬 셋업

from __future__ import annotations

import math
import json
import textwrap
from dataclasses import dataclass, field, asdict
from typing import List, Tuple, Optional, Dict


# ─────────────────────────────────────────────────────────────────────────────
# 설정
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class BlenderBuildConfig:
    """Blender 씬 생성 설정 (모든 단위 mm → Blender는 m 단위로 자동 변환)"""

    # 층 구조
    floor_height_mm: float   = 2800.0   # 층고
    slab_thickness_mm: float = 200.0    # 슬랩 두께
    ceiling_height_mm: float = 2600.0   # 천장고 (층고 - 슬랩)

    # 벽체
    outer_wall_mm: float = 200.0        # 외벽 두께
    inner_wall_mm: float = 100.0        # 내벽 두께
    wall_height_mm: float = 2600.0      # 벽 높이 (= 천장고)

    # 바닥/천장
    add_ceiling: bool = True
    add_floor_slab: bool = True

    # 재질 (Blender material 이름)
    mat_outer_wall: str = "MAT_OuterWall"
    mat_inner_wall: str = "MAT_InnerWall"
    mat_floor: str = "MAT_Floor"
    mat_ceiling: str = "MAT_Ceiling"
    mat_slab: str = "MAT_Slab"

    # 방별 바닥 색상 (room.name → RGBA)
    room_colors: Dict[str, Tuple[float,float,float,float]] = field(default_factory=lambda: {
        "거실":     (0.80, 0.75, 0.60, 1.0),
        "부엌":     (0.70, 0.85, 0.70, 1.0),
        "안방":     (0.65, 0.75, 0.85, 1.0),
        "방2":      (0.85, 0.75, 0.65, 1.0),
        "방3":      (0.75, 0.65, 0.85, 1.0),
        "공용욕실": (0.60, 0.80, 0.85, 1.0),
        "안방욕실": (0.60, 0.75, 0.85, 1.0),
        "현관":     (0.70, 0.70, 0.70, 1.0),
        "드레스룸": (0.85, 0.80, 0.75, 1.0),
        "다용도실": (0.75, 0.80, 0.75, 1.0),
    })

    # 카메라
    camera_distance_m: float = 15.0
    camera_elevation_deg: float = 45.0

    # 스케일 변환
    @property
    def mm_to_m(self) -> float:
        return 0.001


# ─────────────────────────────────────────────────────────────────────────────
# 데이터 구조 (validator.py Room과 독립적 — 직렬화 가능)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class RoomData:
    """직렬화 가능한 방 데이터"""
    name: str
    polygon_mm: List[Tuple[float, float]]
    has_window: bool = False
    connects_to: List[str] = field(default_factory=list)

    @classmethod
    def from_room(cls, room) -> "RoomData":
        """validator.Room → RoomData"""
        return cls(
            name=room.name,
            polygon_mm=list(room.polygon_mm),
            has_window=room.has_window,
            connects_to=list(room.connects_to),
        )


# ─────────────────────────────────────────────────────────────────────────────
# 스크립트 생성기 (핵심)
# ─────────────────────────────────────────────────────────────────────────────

def generate_script(
    pts_mm: List[Tuple[float, float]],
    rooms: Optional[List[RoomData]] = None,
    config: Optional[BlenderBuildConfig] = None,
    scene_name: str = "FloorPlan",
) -> str:
    """
    pts_mm + rooms → Blender Python 스크립트 문자열 반환.

    반환된 문자열을 Blender MCP의 execute_blender_code 또는
    subprocess로 Blender --python 에 전달하면 3D 씬이 생성된다.

    Args:
        pts_mm:     외곽 좌표 리스트 (mm 단위, 이미지 좌표계)
        rooms:      방 배치 리스트 (없으면 외곽+바닥만 생성)
        config:     BlenderBuildConfig (None이면 기본값)
        scene_name: Blender 씬/컬렉션 이름

    Returns:
        실행 가능한 Blender Python 스크립트 문자열
    """
    cfg = config or BlenderBuildConfig()
    rooms = rooms or []

    # pts_mm → Y축 반전 (이미지→CAD) 후 m 변환
    max_y = max(p[1] for p in pts_mm)
    pts_m = [((x * cfg.mm_to_m), ((max_y - y) * cfg.mm_to_m)) for x, y in pts_mm]

    rooms_json = json.dumps([
        {
            "name": r.name,
            "polygon_mm": r.polygon_mm,
            "has_window": r.has_window,
        }
        for r in rooms
    ], ensure_ascii=False)

    room_colors_json = json.dumps(cfg.room_colors, ensure_ascii=False)

    script = textwrap.dedent(f"""
        # ── Auto-generated by blender_builder.py ──────────────────────────
        import bpy
        import bmesh
        import json
        import math
        from mathutils import Vector

        # ── 설정값 ─────────────────────────────────────────────────────────
        SCENE_NAME        = {json.dumps(scene_name)}
        WALL_H            = {cfg.wall_height_mm * cfg.mm_to_m:.4f}   # 벽 높이 (m)
        SLAB_T            = {cfg.slab_thickness_mm * cfg.mm_to_m:.4f} # 슬랩 두께 (m)
        OUTER_WALL_T      = {cfg.outer_wall_mm * cfg.mm_to_m:.4f}     # 외벽 두께 (m)
        INNER_WALL_T      = {cfg.inner_wall_mm * cfg.mm_to_m:.4f}     # 내벽 두께 (m)
        ADD_CEILING       = {cfg.add_ceiling}
        ADD_SLAB          = {cfg.add_floor_slab}
        MM_TO_M           = {cfg.mm_to_m}

        OUTLINE_PTS_M = {pts_m!r}
        ROOMS_DATA    = json.loads({json.dumps(rooms_json)!r})
        ROOM_COLORS   = json.loads({json.dumps(room_colors_json)!r})

        # ── 씬 초기화 ───────────────────────────────────────────────────────
        bpy.ops.object.select_all(action='SELECT')
        bpy.ops.object.delete()
        for col in list(bpy.data.collections):
            bpy.data.collections.remove(col)

        col = bpy.data.collections.new(SCENE_NAME)
        bpy.context.scene.collection.children.link(col)

        def link(obj):
            col.objects.link(obj)
            bpy.context.scene.collection.objects.unlink(obj)

        # ── 재질 팩토리 ─────────────────────────────────────────────────────
        def get_mat(name, rgba=(0.8, 0.8, 0.8, 1.0)):
            if name in bpy.data.materials:
                return bpy.data.materials[name]
            mat = bpy.data.materials.new(name)
            mat.use_nodes = True
            bsdf = mat.node_tree.nodes.get("Principled BSDF")
            if bsdf:
                bsdf.inputs["Base Color"].default_value = rgba
                bsdf.inputs["Roughness"].default_value = 0.7
            return mat

        def assign_mat(obj, mat):
            obj.data.materials.clear()
            obj.data.materials.append(mat)

        # ── 폴리곤 → 메쉬 압출 (공통 함수) ────────────────────────────────
        def extrude_polygon(name, pts_2d, height, z_base=0.0, mat=None):
            \"\"\"pts_2d(XY m) → height(m) 높이로 압출된 메쉬 오브젝트 반환\"\"\"
            me = bpy.data.meshes.new(name + "_mesh")
            bm = bmesh.new()
            verts = [bm.verts.new((x, y, z_base)) for x, y in pts_2d]
            bm.faces.new(verts)
            bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
            bmesh.ops.translate(bm,
                verts=[v for v in bm.verts if v.co.z > z_base + 0.0001],
                vec=(0, 0, height))
            bm.to_mesh(me)
            bm.free()
            obj = bpy.data.objects.new(name, me)
            link(obj)
            if mat:
                assign_mat(obj, mat)
            return obj

        # ── 1. 바닥 슬랩 ────────────────────────────────────────────────────
        if ADD_SLAB:
            slab_mat = get_mat("{cfg.mat_slab}", (0.55, 0.55, 0.55, 1.0))
            extrude_polygon("Slab", OUTLINE_PTS_M, SLAB_T, z_base=-SLAB_T, mat=slab_mat)

        # ── 2. 외벽 ─────────────────────────────────────────────────────────
        # 외벽: 외곽 폴리곤을 압출한 뒤 내부 offset 폴리곤으로 Boolean 차감
        def offset_polygon(pts, d):
            \"\"\"폴리곤 pts를 안쪽으로 d(m) offset (단순 법선 이동)\"\"\"
            import mathutils
            n = len(pts)
            result = []
            for i in range(n):
                p0 = mathutils.Vector((pts[(i-1)%n][0], pts[(i-1)%n][1], 0))
                p1 = mathutils.Vector((pts[i][0],       pts[i][1],       0))
                p2 = mathutils.Vector((pts[(i+1)%n][0], pts[(i+1)%n][1], 0))
                e1 = (p1 - p0).normalized()
                e2 = (p2 - p1).normalized()
                # 각 변의 내부 법선
                n1 = mathutils.Vector((-e1.y,  e1.x, 0))
                n2 = mathutils.Vector((-e2.y,  e2.x, 0))
                # 미터 법선 평균
                bisector = (n1 + n2).normalized()
                sin_half = n1.cross(bisector).z  # sin(half_angle)
                if abs(sin_half) < 1e-6:
                    sin_half = 1.0
                move = bisector * (d / abs(sin_half))
                result.append((p1.x + move.x, p1.y + move.y))
            return result

        outer_mat = get_mat("{cfg.mat_outer_wall}", (0.75, 0.72, 0.68, 1.0))
        outer_shell = extrude_polygon("OuterWall_Shell", OUTLINE_PTS_M, WALL_H, mat=outer_mat)

        inner_pts = offset_polygon(OUTLINE_PTS_M, OUTER_WALL_T)
        inner_void = extrude_polygon("OuterWall_Void", inner_pts, WALL_H + 0.01, z_base=-0.005)

        # Boolean modifier로 차감
        mod = outer_shell.modifiers.new("Hollow", 'BOOLEAN')
        mod.operation = 'DIFFERENCE'
        mod.object    = inner_void
        bpy.context.view_layer.objects.active = outer_shell
        bpy.ops.object.modifier_apply(modifier="Hollow")
        bpy.data.objects.remove(inner_void, do_unlink=True)

        # ── 3. 바닥 면 (방별 색상) ──────────────────────────────────────────
        floor_z = 0.001  # 슬랩 위 1mm

        if ROOMS_DATA:
            for room in ROOMS_DATA:
                rname    = room["name"]
                poly_mm  = room["polygon_mm"]
                max_ry   = max(p[1] for p in poly_mm)
                # 방 폴리곤도 Y축 반전 + mm→m
                poly_m   = [(p[0]*MM_TO_M, (max_ry - p[1])*MM_TO_M) for p in poly_mm]
                rgba     = tuple(ROOM_COLORS.get(rname, (0.7, 0.7, 0.7, 1.0)))
                mat_name = f"MAT_Floor_{{rname}}"
                rmat     = get_mat(mat_name, rgba)
                extrude_polygon(f"Floor_{{rname}}", poly_m, 0.005, z_base=floor_z, mat=rmat)
        else:
            # 방 데이터 없으면 외곽 전체 단색 바닥
            floor_mat = get_mat("{cfg.mat_floor}", (0.85, 0.82, 0.75, 1.0))
            extrude_polygon("Floor", OUTLINE_PTS_M, 0.005, z_base=floor_z, mat=floor_mat)

        # ── 4. 내벽 (방 경계 기준) ──────────────────────────────────────────
        inner_wall_mat = get_mat("{cfg.mat_inner_wall}", (0.88, 0.86, 0.82, 1.0))

        if len(ROOMS_DATA) > 1:
            for i, room_a in enumerate(ROOMS_DATA):
                for j, room_b in enumerate(ROOMS_DATA):
                    if j <= i:
                        continue
                    name_a = room_a["name"]
                    name_b = room_b["name"]
                    poly_a  = room_a["polygon_mm"]
                    poly_b  = room_b["polygon_mm"]
                    max_ay  = max(p[1] for p in poly_a)
                    max_by  = max(p[1] for p in poly_b)
                    pts_a_m = [(p[0]*MM_TO_M, (max_ay-p[1])*MM_TO_M) for p in poly_a]
                    pts_b_m = [(p[0]*MM_TO_M, (max_by-p[1])*MM_TO_M) for p in poly_b]

                    # 공유 엣지(인접 변) 탐색
                    shared = _find_shared_edges(pts_a_m, pts_b_m, tol=INNER_WALL_T * 2)
                    for k, (p1, p2) in enumerate(shared):
                        seg_len = math.sqrt((p2[0]-p1[0])**2 + (p2[1]-p1[1])**2)
                        if seg_len < 0.05:
                            continue
                        wall_name = f"IWall_{{name_a}}_{{name_b}}_{{k}}"
                        _build_wall_segment(wall_name, p1, p2, WALL_H, INNER_WALL_T, inner_wall_mat)

        # ── 5. 천장 ─────────────────────────────────────────────────────────
        if ADD_CEILING:
            ceil_mat = get_mat("{cfg.mat_ceiling}", (0.95, 0.95, 0.95, 1.0))
            extrude_polygon("Ceiling", OUTLINE_PTS_M, 0.02, z_base=WALL_H, mat=ceil_mat)

        # ── 6. 카메라 & 조명 ────────────────────────────────────────────────
        # 씬 중심 계산
        cx = sum(p[0] for p in OUTLINE_PTS_M) / len(OUTLINE_PTS_M)
        cy = sum(p[1] for p in OUTLINE_PTS_M) / len(OUTLINE_PTS_M)
        cam_dist = {cfg.camera_distance_m}
        elev_rad = math.radians({cfg.camera_elevation_deg})

        cam_data = bpy.data.cameras.new("Camera")
        cam_obj  = bpy.data.objects.new("Camera", cam_data)
        link(cam_obj)
        cam_obj.location = (cx + cam_dist * math.cos(elev_rad),
                            cy - cam_dist * math.cos(elev_rad),
                            cam_dist * math.sin(elev_rad))
        cam_obj.rotation_euler = (
            math.radians(90 - {cfg.camera_elevation_deg}),
            0,
            math.radians(45),
        )
        bpy.context.scene.camera = cam_obj

        # 3점 조명
        for name, loc, energy in [
            ("Key",   (cx+8,  cy-5,  10), 1500),
            ("Fill",  (cx-6,  cy+4,   8),  600),
            ("Back",  (cx+2,  cy+10,  6),  400),
        ]:
            ld = bpy.data.lights.new(name, 'POINT')
            ld.energy = energy
            lo = bpy.data.objects.new(name, ld)
            link(lo)
            lo.location = loc

        # ── 7. 뷰포트 설정 ──────────────────────────────────────────────────
        for area in bpy.context.screen.areas:
            if area.type == 'VIEW_3D':
                for space in area.spaces:
                    if space.type == 'VIEW_3D':
                        space.shading.type = 'MATERIAL'
                        space.region_3d.view_perspective = 'CAMERA'
                break

        print(f"[blender_builder] 씬 생성 완료 — 외곽 {{len(OUTLINE_PTS_M)}}pts, 방 {{len(ROOMS_DATA)}}개")

        # ─── 인접 변 탐색 (내벽 생성용) ────────────────────────────────────
        def _find_shared_edges(pts_a, pts_b, tol=0.15):
            shared = []
            for i in range(len(pts_a)):
                p1a = pts_a[i]
                p2a = pts_a[(i+1) % len(pts_a)]
                for j in range(len(pts_b)):
                    p1b = pts_b[j]
                    p2b = pts_b[(j+1) % len(pts_b)]
                    if (_pt_near(p1a, p1b, tol) and _pt_near(p2a, p2b, tol)) or \
                       (_pt_near(p1a, p2b, tol) and _pt_near(p2a, p1b, tol)):
                        shared.append((p1a, p2a))
            return shared

        def _pt_near(a, b, tol):
            return math.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2) < tol

        def _build_wall_segment(name, p1, p2, height, thickness, mat):
            dx = p2[0] - p1[0]
            dy = p2[1] - p1[1]
            length = math.sqrt(dx*dx + dy*dy)
            if length < 1e-4:
                return
            mx, my = (p1[0]+p2[0])/2, (p1[1]+p2[1])/2
            angle  = math.atan2(dy, dx)
            bpy.ops.mesh.primitive_cube_add(
                size=1,
                location=(mx, my, height/2),
            )
            obj = bpy.context.active_object
            obj.name = name
            obj.scale = (length, thickness, height)
            obj.rotation_euler[2] = angle
            bpy.ops.object.transform_apply(scale=True, rotation=True)
            col.objects.link(obj)
            try:
                bpy.context.scene.collection.objects.unlink(obj)
            except Exception:
                pass
            assign_mat(obj, mat)
    """).strip()

    return script


# ─────────────────────────────────────────────────────────────────────────────
# 파일 저장 유틸리티
# ─────────────────────────────────────────────────────────────────────────────

def save_script(script: str, output_path: str) -> str:
    """생성된 스크립트를 .py 파일로 저장"""
    import os
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script)
    return output_path


def generate_script_from_result(
    extraction_result,
    rooms=None,
    config: Optional[BlenderBuildConfig] = None,
    scene_name: str = "FloorPlan",
) -> str:
    """
    extractor.ExtractionResult + [validator.Room 리스트] → 스크립트 문자열

    Usage:
        from extractor import extract_outline
        from blender_builder import generate_script_from_result

        result = extract_outline("plan.png", known_area_m2=58.49)
        script = generate_script_from_result(result)
        # → Blender MCP로 전달
    """
    room_data_list = []
    if rooms:
        for r in rooms:
            if hasattr(r, "polygon_mm"):
                room_data_list.append(RoomData.from_room(r))
            else:
                room_data_list.append(r)  # 이미 RoomData인 경우

    return generate_script(
        pts_mm=list(extraction_result.pts_mm),
        rooms=room_data_list,
        config=config,
        scene_name=scene_name,
    )
